import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import NextAuthProvider from "./context/NextAuthProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log("session in layout", session);
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextAuthProvider>
          <Header userSession={session} />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
